version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: movieapp-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: movies-app
      MYSQL_USER: movieapp
      MYSQL_PASSWORD: movieapp123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./movies-app.sql:/docker-entrypoint-initdb.d/movies-app.sql
    networks:
      - movieapp-network

  # Backend API
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: movieapp-backend
    restart: unless-stopped
    environment:
      DB_HOST: mysql
      DB_DATABASE: movies-app
      DB_USERNAME: movieapp
      DB_PASSWORD: movieapp123
      SECRET_TOKEN: movie-app-secret-key-2024
      PORT: 3000
      NODE_ENV: production
      DEV_HOST: http://localhost:4200
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - movieapp-network

  # Frontend (Development)
  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    container_name: movieapp-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
    volumes:
      - ./front_end:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - movieapp-network

volumes:
  mysql_data:

networks:
  movieapp-network:
    driver: bridge 